### PR TITLE
fix flash header detection

### PR DESCRIPTION
**Pull request by hupster**

### CODE REVIEW

**Comment by ezflash** [comment]
First look seems pretty good to me. I will need some time to check it. I would prefer the DLL version to be consistent over platform. ie move the linux arm to 6.50 or move the other platforms to 6.82.

**Comment by hupster** [comment]
Understand, actually prefer same DLL versions too but also tried to minimize my changes.
Not sure if you want the reset after flash and version bump, I just had to bring it to a state where we can use it in production.

Thanks for creating this anyway, it's way simpler than the other solutions that I found!

**Comment by ezflash** [comment]
The reset is cool. I may had an option to not reset, but I think having by default is the correct thing. 

I'm puzzled about the _fix flash header detection_. Which python version do you use?

**Comment by hupster** [comment]
We're using version 3.5.3-1: https://packages.debian.org/stretch/python3

I'm actually new to Python, but the header detection didn't work for me and I got "Not a bootable image" on a valid image that already had the header. Seemed like a quick fix because the check for "fileData[3] != 0x7" worked and should be the same anyway I reckoned.

**Review by ezflash — APPROVED** [review]

**Pull request merged**
